name: Development pipeline

on:
  push:
    branches: [dev]

jobs:
  Test_and_Lint:
    name: Testing and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          npm i
      - name: Run linting
        run: |
          echo "Running Linting"
          npm run lint
      - name: Run Tests
        run: |
          echo "Running  tests..."
          npm run test:ci
        env:
          CI: true
  securityCheck:
    name: security check
    runs-on: ubuntu-latest
    steps:
      - name: Checking Security
        run: |
          echo "Runing Securit Checks"

  Deploy-Preview:
    name: Deploy to Preview on vercel
    needs: [Test_and_Lint, securityCheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} #required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required

