name: Development pipeline

on:
  push:
    branches: [dev]

jobs:
  Test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          npm i
      - name: Run Tests
        run: |
          echo "Running  tests..."
          npm run test:ci
        env:
          CI: true
  securityCheck:
    name: security check
    runs-on: ubuntu-latest
    steps:
      - name: Checking Security
        run: |
          echo "Runing Securit Checks"

  Deploy-Preview:
    name: Deploy to Preview on vercel
    needs: [Test, securityCheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          vercel build  --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt  --token=${{ secrets.VERCEL_TOKEN }}
